//! Payoffs for path-dependent exotic options.
//!
//! Every payoff implements [`Payoff::evaluate`], which receives a fully
//! simulated path and returns the **present value** of all cashflows
//! generated by that path (i.e. already discounted to t = 0). Returning
//! a PV uniformly handles products with intermediate cashflows
//! (autocallables, cliquets with periodic settlement) without forcing
//! the engine to know about settlement schedules.
//!
//! Convention: `path[0]` is the spot at t = 0 and `path[i]` is the price
//! at t = i * dt.
//!
//! Whether the t = 0 fixing counts as an observation follows the market
//! convention for each contract rather than a single blanket rule:
//!
//! * **Barrier** and **lookback** monitor the *whole* path including
//!   `path[0]`. A barrier contract that is already through its barrier at
//!   inception knocks out (or in) immediately, and a lookback's running
//!   extremum starts at the initial fixing.
//! * **Asian** averages over `path[1..=N]` only - averaging windows
//!   conventionally exclude the initial fixing.
//! * **Cliquet** reads returns `path[i]/path[i-1]` from `i = 1`, so
//!   `path[0]` anchors the first period without being an observation in
//!   its own right.
//! * **Autocallable** observes exactly the indices it is given.

use crate::error::PricingError;

/// Direction of a vanilla option.
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum OptionType {
    Call,
    Put,
}

impl OptionType {
    /// Intrinsic value `max(S - K, 0)` for a call, `max(K - S, 0)` for a put.
    #[inline]
    pub fn intrinsic(&self, spot: f64, strike: f64) -> f64 {
        match self {
            OptionType::Call => (spot - strike).max(0.0),
            OptionType::Put => (strike - spot).max(0.0),
        }
    }
}

/// Trait implemented by every exotic payoff.
///
/// `dt` is the simulation time step and `r` is the risk-free rate; both
/// come from the path generator and are forwarded by the engine so the
/// payoff can discount intermediate cashflows.
pub trait Payoff: Send + Sync {
    fn evaluate(&self, path: &[f64], dt: f64, r: f64) -> f64;

    /// Check this payoff against the model it is about to be priced under.
    ///
    /// The engine calls this once per run, before simulating anything, so
    /// a misconfigured payoff surfaces as a single error rather than as a
    /// panic from inside every worker thread. The default implementation
    /// accepts everything, so existing and third-party payoffs that have
    /// nothing to check are unaffected.
    fn validate(&self, _steps: usize) -> Result<(), PricingError> {
        Ok(())
    }
}

// -----------------------------------------------------------------------
// European
// -----------------------------------------------------------------------

/// Plain vanilla European option. Useful as a sanity check against
/// closed-form Black-Scholes prices.
#[derive(Clone, Debug)]
pub struct EuropeanOption {
    pub option_type: OptionType,
    pub strike: f64,
}

impl Payoff for EuropeanOption {
    fn evaluate(&self, path: &[f64], dt: f64, r: f64) -> f64 {
        let t = dt * (path.len() - 1) as f64;
        let terminal = *path.last().expect("path must be non-empty");
        (-r * t).exp() * self.option_type.intrinsic(terminal, self.strike)
    }
}

// -----------------------------------------------------------------------
// Asian (arithmetic average)
// -----------------------------------------------------------------------

/// Arithmetic-average Asian option. The averaging window is the set of
/// monitoring dates `path[1..=N]`. Geometric averaging is not supported
/// here because it admits a closed form and benefits less from MC.
#[derive(Clone, Debug)]
pub struct AsianOption {
    pub option_type: OptionType,
    pub strike: f64,
}

impl Payoff for AsianOption {
    fn evaluate(&self, path: &[f64], dt: f64, r: f64) -> f64 {
        let n = path.len() - 1;
        let avg: f64 = path[1..].iter().sum::<f64>() / n as f64;
        let t = dt * n as f64;
        (-r * t).exp() * self.option_type.intrinsic(avg, self.strike)
    }
}

// -----------------------------------------------------------------------
// Barrier
// -----------------------------------------------------------------------

/// All eight standard barrier flavours (up/down x in/out x call/put).
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
pub enum BarrierKind {
    UpAndOut,
    UpAndIn,
    DownAndOut,
    DownAndIn,
}

/// Discretely-monitored barrier option. Monitoring happens on the
/// simulation grid, so a finer `steps` count in the model produces a
/// price closer to the continuously-monitored limit. For continuous
/// monitoring with a coarse grid, apply a Broadie-Glasserman-Kou shift
/// to the barrier before constructing the payoff (not done automatically
/// here - the caller may want either convention).
#[derive(Clone, Debug)]
pub struct BarrierOption {
    pub option_type: OptionType,
    pub kind: BarrierKind,
    pub strike: f64,
    pub barrier: f64,
    /// Cash rebate paid at maturity if the option ends up worthless due
    /// to the barrier event (for "out" options) or because the barrier
    /// was never hit (for "in" options). Set to 0.0 for the textbook
    /// rebate-free contract.
    pub rebate: f64,
}

impl Payoff for BarrierOption {
    fn evaluate(&self, path: &[f64], dt: f64, r: f64) -> f64 {
        let n = path.len() - 1;
        let t = dt * n as f64;
        let disc = (-r * t).exp();
        let terminal = path[n];

        // Monitoring includes the t = 0 fixing: a contract already through
        // its barrier at inception is knocked out (or in) straight away.
        let hit = match self.kind {
            BarrierKind::UpAndOut | BarrierKind::UpAndIn => path.iter().any(|&s| s >= self.barrier),
            BarrierKind::DownAndOut | BarrierKind::DownAndIn => {
                path.iter().any(|&s| s <= self.barrier)
            }
        };

        let alive = match self.kind {
            BarrierKind::UpAndOut | BarrierKind::DownAndOut => !hit,
            BarrierKind::UpAndIn | BarrierKind::DownAndIn => hit,
        };

        if alive {
            disc * self.option_type.intrinsic(terminal, self.strike)
        } else {
            disc * self.rebate
        }
    }
}

// -----------------------------------------------------------------------
// Lookback
// -----------------------------------------------------------------------

/// Lookback option, discretely monitored on the simulation grid.
///
/// * Floating strike call:  `S_T - min(S)`
/// * Floating strike put :  `max(S) - S_T`
/// * Fixed    strike call:  `max(max(S) - K, 0)`
/// * Fixed    strike put :  `max(K - min(S), 0)`
#[derive(Clone, Debug)]
pub struct LookbackOption {
    pub option_type: OptionType,
    /// `Some(K)` for a fixed-strike lookback, `None` for floating strike.
    pub strike: Option<f64>,
}

impl Payoff for LookbackOption {
    fn evaluate(&self, path: &[f64], dt: f64, r: f64) -> f64 {
        let n = path.len() - 1;
        let t = dt * n as f64;
        let disc = (-r * t).exp();
        let terminal = path[n];
        // The running extremum includes the initial fixing, so a floating
        // strike can never be worse than the spot the contract started at.
        let max_s = path.iter().cloned().fold(f64::NEG_INFINITY, f64::max);
        let min_s = path.iter().cloned().fold(f64::INFINITY, f64::min);

        let payoff = match (self.option_type, self.strike) {
            (OptionType::Call, None) => terminal - min_s,
            (OptionType::Put, None) => max_s - terminal,
            (OptionType::Call, Some(k)) => (max_s - k).max(0.0),
            (OptionType::Put, Some(k)) => (k - min_s).max(0.0),
        };
        disc * payoff
    }
}

// -----------------------------------------------------------------------
// Cliquet (sum of locally-capped/floored returns)
// -----------------------------------------------------------------------

/// Cliquet (aka ratchet) option. Pays the sum of periodic returns,
/// each clamped to a local cap and floor, with an optional global floor
/// applied to the running total at maturity.
///
/// Period boundaries are the monitoring dates of the path: with `N`
/// simulation steps the cliquet has `N` periods, each of length `dt`.
/// A coarser cliquet schedule can be obtained by reducing the model's
/// `steps` to match the desired periods.
#[derive(Clone, Debug)]
pub struct CliquetOption {
    pub notional: f64,
    pub local_floor: f64,
    pub local_cap: f64,
    pub global_floor: f64,
    pub global_cap: f64,
}

impl Payoff for CliquetOption {
    fn evaluate(&self, path: &[f64], dt: f64, r: f64) -> f64 {
        let n = path.len() - 1;
        let mut sum = 0.0;
        for i in 1..=n {
            let ret = path[i] / path[i - 1] - 1.0;
            sum += ret.max(self.local_floor).min(self.local_cap);
        }
        let total = sum.max(self.global_floor).min(self.global_cap);
        let t = dt * n as f64;
        (-r * t).exp() * self.notional * total
    }
}

// -----------------------------------------------------------------------
// Autocallable note
// -----------------------------------------------------------------------

/// Single-underlying autocallable note with discrete observation dates.
///
/// On each observation date the note redeems early at par plus an
/// accrued coupon if the spot is at or above `autocall_barrier`.
/// Otherwise, at maturity:
///   * if `S_T >= protection_barrier` the note pays `notional + coupon`,
///   * else the investor takes equity exposure: `notional * S_T / S_0`.
///
/// `observation_indices` selects which simulation steps are observation
/// dates, indexing directly into the path. The final index is treated as
/// maturity. The schedule must be non-empty, strictly increasing, and
/// within the model's step count; this is checked once per pricing run by
/// [`Payoff::validate`], so a bad schedule is reported as a
/// [`PricingError`] rather than panicking inside every worker thread.
/// Index 0 is legal and means "observe at inception".
#[derive(Clone, Debug)]
pub struct AutocallableNote {
    pub notional: f64,
    pub coupon_per_period: f64,
    pub autocall_barrier: f64,
    pub protection_barrier: f64,
    pub observation_indices: Vec<usize>,
}

impl Payoff for AutocallableNote {
    fn validate(&self, steps: usize) -> Result<(), PricingError> {
        let Some(&first) = self.observation_indices.first() else {
            return Err(PricingError::EmptyObservationSchedule);
        };
        let mut previous = first;
        for (position, &index) in self.observation_indices.iter().enumerate() {
            if index > steps {
                return Err(PricingError::ObservationOutOfRange { index, steps });
            }
            if position > 0 && index <= previous {
                return Err(PricingError::UnorderedObservationSchedule {
                    previous,
                    next: index,
                });
            }
            previous = index;
        }
        Ok(())
    }

    fn evaluate(&self, path: &[f64], dt: f64, r: f64) -> f64 {
        let s0 = path[0];
        let last_obs = *self
            .observation_indices
            .last()
            .expect("autocallable needs at least one observation");

        for (period, &idx) in self.observation_indices.iter().enumerate() {
            let s = path[idx];
            let t = dt * idx as f64;
            let is_final = idx == last_obs;

            if s >= self.autocall_barrier && !is_final {
                let cf = self.notional + self.coupon_per_period * (period + 1) as f64;
                return (-r * t).exp() * cf;
            }
            if is_final {
                let cf = if s >= self.protection_barrier {
                    self.notional + self.coupon_per_period * (period + 1) as f64
                } else {
                    self.notional * s / s0
                };
                return (-r * t).exp() * cf;
            }
        }
        unreachable!("loop returns on the final observation");
    }
}
